---
install:
  - git clone git://github.com/travis-perl/helpers.git travis-perl-helpers
  - source travis-perl-helpers/init
  - cpanm --notest --with-recommends --with-suggests Test::WriteVariants Config::AutoConf Carp inc::latest
  - perl Makefile.PL
  - make manifest
  - cpanm --notest --with-recommends --with-suggests --with-develop --installdeps .
  - cpan-install --coverage
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26-shrplib"
  - "5.26"
  - "5.24-shrplib"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
matrix:
  include:
    - perl: "5.30"
      env: COVERAGE=1
    - perl: "5.30"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
    - perl: "5.28"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
    - perl: "5.26"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
    - perl: "5.26-shrplib"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
    - perl: "5.24-shrplib"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
    - perl: "5.18"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
    - perl: "5.14"
      env: PERL_MM_OPT="PUREPERL_ONLY=1"
before_script:
  - coverage-setup
after_success:
  - coverage-report
